/*
 * JFFixIdentify.java
 *
 * Created on 05 September 2007, 23:40
 */

package elicit.tools;

import elicit.message.Message;
import javax.swing.JDialog;

/**
 *
 * @author  Marco
 */
public class FixIDDialog extends JDialog {
                        //implements ActionListener,
                        //PropertyChangeListener 
    
    static public String m_answerText;
    static public String m_who;
    static public String m_what;
    static public String m_where;
    static public String m_when;
    
    static public double m_scoreWho;
    static public double m_scoreWhat;
    static public double m_scoreWhere;
    static public double m_scoreWhen;
    
    public double m_valueWrongh = -0.25;
    public double m_valueNone = 0;
    public double m_valueRight = 0.25;
    
    /** Creates new form JFFixIdentify */
    public FixIDDialog() {
        //handle UI
        tools.UItools.UITools.setNativeLookAndFeel();
        setModalityType(ModalityType.APPLICATION_MODAL);
        
        initComponents();
        //set default values in group button (all none)
        jrbWhoNone.setSelected(true);
        jrbWhatNone.setSelected(true);
        jrbWhereNone.setSelected(true);
        jrbWhenNone.setSelected(true);
    }
    
    public void setIDText (String text_p) {
        jlIDText.setText(text_p);
    }  
    
    public void setWhoText (String text_p) {
        /*
        if (text_p!=null && text_p.equals(elicit.message.IdentifyMessage.m_whoText)) {
            jrbWhoNone.setSelected(true);
        }
        else {
            jrbWhoWrongh.setSelected(true);
        }
         */
        jlWho.setText(text_p);
    }
    
    public void setWhatText (String text_p) {
        /*
        if (text_p!=null && text_p.equals(elicit.message.IdentifyMessage.m_whatText)) {
            jrbWhatNone.setSelected(true);
        }
        else {
            jrbWhatWrongh.setSelected(true);
        }
        jlWhat.setText(text_p);
         */
    }
    
    public void setWhereText (String text_p) {
//        if (text_p!=null && text_p.equals(elicit.message.IdentifyMessage.m_whereText)) {
//            jrbWhereNone.setSelected(true);
//        }
//        else {
//            jrbWhereWrongh.setSelected(true);
//        }
//        jlWhere.setText(text_p);
    }
    
    public void setWhenText (String text_p) {
//        if (text_p!=null && text_p.equals(elicit.message.IdentifyMessage.m_whenText)) {
//            jrbWhenNone.setSelected(true);
//        }
//        else {
//            jrbWhenWrongh.setSelected(true);
//        }
//        jlWhen.setText(text_p);
    }
    
    public double getWhoScore() {
        if (jrbWhoWrongh.isSelected()) {
            return m_valueWrongh;
        }
        else if (jrbWhoRight.isSelected()) {
            return m_valueRight;
        }
        else {
            return m_valueNone;
        }
    }
    
    public double getWhatScore() {
        if (jrbWhatWrongh.isSelected()) {
            return m_valueWrongh;
        }
        else if (jrbWhatRight.isSelected()) {
            return m_valueRight;
        }
        else {
            return m_valueNone;
        }
    }
    
    public double getWhereScore() {
        if (jrbWhereWrongh.isSelected()) {
            return m_valueWrongh;
        }
        else if (jrbWhereRight.isSelected()) {
            return m_valueRight;
        }
        else {
            return m_valueNone;
        }
    }
    
    public double getWhenScore() {
        if (jrbWhenWrongh.isSelected()) {
            return m_valueWrongh;
        }
        else if (jrbWhenRight.isSelected()) {
            return m_valueRight;
        }
        else {
            return m_valueNone;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jbgWho = new javax.swing.ButtonGroup();
        jbgWhat = new javax.swing.ButtonGroup();
        jbgWhere = new javax.swing.ButtonGroup();
        jbgWhen = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jpIdentify = new javax.swing.JPanel();
        jlIDText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlWho = new javax.swing.JLabel();
        jlWhat = new javax.swing.JLabel();
        jlWhere = new javax.swing.JLabel();
        jlWhen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jrbWhoWrongh = new javax.swing.JRadioButton();
        jrbWhoNone = new javax.swing.JRadioButton();
        jrbWhoRight = new javax.swing.JRadioButton();
        jrbWhatWrongh = new javax.swing.JRadioButton();
        jrbWhatNone = new javax.swing.JRadioButton();
        jrbWhatRight = new javax.swing.JRadioButton();
        jrbWhereWrongh = new javax.swing.JRadioButton();
        jrbWhereNone = new javax.swing.JRadioButton();
        jrbWhereRight = new javax.swing.JRadioButton();
        jrbWhenWrongh = new javax.swing.JRadioButton();
        jrbWhenNone = new javax.swing.JRadioButton();
        jrbWhenRight = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jbOK = new javax.swing.JButton();

        jbgWho.add(jrbWhoWrongh);
        jbgWho.add(jrbWhoNone);
        jbgWho.add(jrbWhoRight);
        jbgWhat.add(jrbWhatWrongh);
        jbgWhat.add(jrbWhatNone);
        jbgWhat.add(jrbWhatRight);
        jbgWhere.add(jrbWhereWrongh);
        jbgWhere.add(jrbWhereNone);
        jbgWhere.add(jrbWhereRight);
        jbgWhen.add(jrbWhenWrongh);
        jbgWhen.add(jrbWhenNone);
        jbgWhen.add(jrbWhenRight);

        setTitle("Fix Identify");
        setResizable(false);
        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fix Identify");
        jLabel1.setOpaque(true);

        jpIdentify.setBorder(javax.swing.BorderFactory.createTitledBorder("Identification Answer"));
        jlIDText.setText("<answer>");

        javax.swing.GroupLayout jpIdentifyLayout = new javax.swing.GroupLayout(jpIdentify);
        jpIdentify.setLayout(jpIdentifyLayout);
        jpIdentifyLayout.setHorizontalGroup(
            jpIdentifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIdentifyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpIdentifyLayout.setVerticalGroup(
            jpIdentifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Player Identify Data"));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Who");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("What");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Where");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("When");

        jlWho.setText("<who answer>");

        jlWhat.setText("<what answer>");

        jlWhere.setText("<where answer>");

        jlWhen.setText("<when answer>");

        jLabel2.setText("Wrong");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("None");

        jLabel9.setText("Right");

        jrbWhoWrongh.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhoWrongh.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhoNone.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhoNone.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhoRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhoRight.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhatWrongh.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhatWrongh.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhatNone.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhatNone.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhatRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhatRight.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhereWrongh.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhereWrongh.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhereNone.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhereNone.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhereRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhereRight.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhenWrongh.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhenWrongh.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhenNone.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhenNone.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrbWhenRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbWhenRight.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlWhen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlWhere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlWhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlWho, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbWhatWrongh)
                            .addComponent(jrbWhoWrongh)
                            .addComponent(jrbWhereWrongh)
                            .addComponent(jrbWhenWrongh))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbWhatNone)
                            .addComponent(jrbWhoNone)
                            .addComponent(jrbWhereNone)
                            .addComponent(jrbWhenNone))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbWhatRight)
                            .addComponent(jrbWhoRight)
                            .addComponent(jrbWhereRight)
                            .addComponent(jrbWhenRight))))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jlWho)
                                .addComponent(jrbWhoWrongh))
                            .addComponent(jrbWhoNone))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jrbWhoRight, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jlWhat))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlWhere))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlWhen)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbWhatWrongh)
                                    .addComponent(jrbWhatNone))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbWhereWrongh)
                                    .addComponent(jrbWhereNone)
                                    .addComponent(jrbWhereRight, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jrbWhatRight, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbWhenWrongh)
                            .addComponent(jrbWhenNone)
                            .addComponent(jrbWhenRight, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(62, 62, 62))
        );

        jbOK.setText("OK");
        jbOK.setPreferredSize(new java.awt.Dimension(80, 25));
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addComponent(jpIdentify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpIdentify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbOK;
    private javax.swing.ButtonGroup jbgWhat;
    private javax.swing.ButtonGroup jbgWhen;
    private javax.swing.ButtonGroup jbgWhere;
    private javax.swing.ButtonGroup jbgWho;
    private javax.swing.JLabel jlIDText;
    private javax.swing.JLabel jlWhat;
    private javax.swing.JLabel jlWhen;
    private javax.swing.JLabel jlWhere;
    private javax.swing.JLabel jlWho;
    private javax.swing.JPanel jpIdentify;
    private javax.swing.JRadioButton jrbWhatNone;
    private javax.swing.JRadioButton jrbWhatRight;
    private javax.swing.JRadioButton jrbWhatWrongh;
    private javax.swing.JRadioButton jrbWhenNone;
    private javax.swing.JRadioButton jrbWhenRight;
    private javax.swing.JRadioButton jrbWhenWrongh;
    private javax.swing.JRadioButton jrbWhereNone;
    private javax.swing.JRadioButton jrbWhereRight;
    private javax.swing.JRadioButton jrbWhereWrongh;
    private javax.swing.JRadioButton jrbWhoNone;
    private javax.swing.JRadioButton jrbWhoRight;
    private javax.swing.JRadioButton jrbWhoWrongh;
    // End of variables declaration//GEN-END:variables
    
}
